spring:
  datasource:
   url: jdbc:mysql://localhost:3306/my_items2?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
   username: root
   password: root

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8081

jwt:
  expiration: 330000
  secret: 2ljfl%4k5j4l32@@FLDKFLDS

myitems:
  cb:
   url: https://cb.am/latest.json.php

logging:
  logback:
   rollingpolicy:
     file-name-pattern:  ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz # by date
     max-file-size:  10MB # by size
 file:
    name: C:\Users\Gohar\IdeaProjects\myItemsRest\log\application-log.log
 pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: info
    com.example: info

